### PR TITLE
Antispam

### PR DESCRIPTION
**Pull request by Akarys42**
This PR adds the base of antispam extensions, with some already defined filters : 
* Maximum number of messages sent in 10 seconds.
* Maximum number of the same message sent in 10 seconds.
* Maximum number of mentions in 5 seconds.
* Maximum number of links sent in 5 seconds.
* Maximum number of emojis sent in 5 seconds.

Note : I'm getting a `UnnecessaryAbstractClass` on the `Antispam` ABC, what am I doing wrong?

### CODE REVIEW

**Comment by gdude2002** [comment]
> Note: I'm getting a `UnnecessaryAbstractClass` on the `Antispam` ABC, what am I doing wrong?

If an abstract class has no concrete (non-abstract) members, it should be an interface.

**Comment by Akarys42** [comment]
The PR is blocked until the infraction system is working and we have a proper API to store the context. :grin:

**Comment by gdude2002** [comment]
The API is in place. Storing cleaned messages is currently out of scope, but this is no longer blocked.

**Comment by gdude2002** [comment]
We should focus this PR so that we can port to the new version of Kord.

**Comment by gdude2002** [comment]
This has stalled massively, and I have a better understanding of how this kind of extension should work now. As I'm going to be updating the bot to the latest KordEx soon, this PR would need to be rewritten entirely anyway - and besides, the site's DB stuff needs redoing too.

**Pull request closed without merging**
